AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for AWS Lambda source code

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-lambda-source-${AWS::Region}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowServerlessRepoToGetSourceCode
            Action: s3:GetObject
            Effect: Allow
            Resource: !Sub ${Bucket.Arn}/*
            Principal:
              Service: serverlessrepo.amazonaws.com

Outputs:
  BucketName:
    Description: The name of the S3 Bucket.
    Value: !Ref Bucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName
  BucketArn:
    Description: The Arn of the S3 Bucket.
    Value: !GetAtt Bucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-BucketArn
